services:
  renovate:
    image: renovate/renovate:latest
    environment:
      RENOVATE_TOKEN: ${RENOVATE_TOKEN}
      RENOVATE_PLATFORM: ${RENOVATE_PLATFORM:-github}
      RENOVATE_ENDPOINT: ${RENOVATE_ENDPOINT:-}
      RENOVATE_REPOSITORIES: ${RENOVATE_REPOSITORIES}
      RENOVATE_REQUIRE_CONFIG: required
      LOG_LEVEL: ${LOG_LEVEL:-info}
