services:
  renovate:
    image: renovate/renovate:latest
    volumes:
      - ../:/usr/src/app:ro
    working_dir: /usr/src/app
    environment:
      RENOVATE_TOKEN: ${RENOVATE_TOKEN}
      RENOVATE_PLATFORM: ${RENOVATE_PLATFORM:-github}
      RENOVATE_ENDPOINT: ${RENOVATE_ENDPOINT:-}
      RENOVATE_REPOSITORIES: ${RENOVATE_REPOSITORIES}
      RENOVATE_REQUIRE_CONFIG: optional
      LOG_LEVEL: ${LOG_LEVEL:-info}
